setInterval(function responsiveBackground(){
	if(window.innerHeight>window.innerWidth)
	{
		document.getElementById("box").style.width="100%";
		document.getElementById("box2").style.width="100%";
		document.getElementById("shootButton").style.left="0%";
		document.getElementById("shootButton").style.width="33.3%";
		document.getElementById("shootTable").style.width="100%";
		document.getElementById("shootTable").style.left="0%";
		document.getElementById("scoreBox").style.right="4%";
		document.getElementById("scoreBox").style.width="100%";
		document.getElementById("scoreText").style.fontSize="250%";
		document.getElementById("credits").style.fontSize="150%";
		document.getElementById("credits").style.right="2%";
	}
	else if(window.innerHeight<window.innerWidth)
	{
		document.getElementById("box").style.width="35%";
		document.getElementById("box2").style.width="35%";
		document.getElementById("shootButton").style.left="32.5%";
		document.getElementById("shootButton").style.width="10%";
		document.getElementById("shootTable").style.width="35%";
		document.getElementById("shootTable").style.left="32.5%";
		document.getElementById("scoreBox").style.right="34%";
		document.getElementById("scoreBox").style.width="32%";
		document.getElementById("scoreText").style.fontSize="150%";
		document.getElementById("credits").style.fontSize="120%";
		document.getElementById("credits").style.right="33.5%";
	}
	else
	{
		document.getElementById("box").style.width="35%";
		document.getElementById("box2").style.width="35%";
		document.getElementById("shootButton").style.left="32.5%";
		document.getElementById("shootButton").style.width="10%";
		document.getElementById("shootTable").style.width="35%";
		document.getElementById("shootTable").style.left="32.5%";
		document.getElementById("scoreBox").style.right="34%";
		document.getElementById("scoreBox").style.width="32%";
		document.getElementById("scoreText").style.fontSize="150%";
		document.getElementById("credits").style.fontSize="120%";
		document.getElementById("credits").style.right="33.5%";
	}
},100);